#!/bin/bash

GRAPH=enron_undirected
INPUT_GRAPH=/giraphpp/$GRAPH
NUM_PARTITIONS=15
NUM_REDUCERS=15
NUM_NODES=16343

OUTPUT_GRAPH=$INPUT_GRAPH.recoded
COARSEN_GRAPH=$INPUT_GRAPH.coarsen
METIS_GRAPH=$INPUT_GRAPH.metis
METIS_MAPPING=$INPUT_GRAPH.metis.mapping
METIS_BACK_MAPPING=$INPUT_GRAPH.metis.back.mapping
WCC_GRAPH=$INPUT_GRAPH.wcc
WCC_OUT=$INPUT_GRAPH.wcc.out
NODE_MAPPNG=$INPUT_GRAPH.mapping
BREAKPOINTS=$OUTPUT_GRAPH.breakpoints
ORPHANS=$INPUT_GRAPH.orphans

hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.CoarsenVertex $INPUT_GRAPH $NUM_REDUCERS $COARSEN_GRAPH $NUM_PARTITIONS

hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.PrepareMetisInputMapping $COARSEN_GRAPH $METIS_MAPPING local.metis

hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.PrepareMetisInputGraph $COARSEN_GRAPH $METIS_MAPPING $METIS_GRAPH local.metis $NUM_REDUCERS



# call metis


hadoop dfs -cat $METIS_GRAPH/part* >> local.metis
gpmetis local.metis $NUM_PARTITIONS -contig > local.metis.part.$NUM_PARTITIONS.log

#map partitiion id to vertex id
hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.MapMetisResultsBack local.metis local.metis.part.$NUM_PARTITIONS $METIS_MAPPING/part-r-00000 $METIS_BACK_MAPPING

#prepare input for wcc
hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.PrepareInputForWCC $COARSEN_GRAPH  $METIS_BACK_MAPPING/_temporary/_attempt__0000_r_000000_0/part-r-00000 $WCC_GRAPH $NUM_PARTITIONS

# run wcc
hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.wcc.WCCGraph $WCC_GRAPH $WCC_OUT $NUM_REDUCERS true $NUM_REDUCERS

hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.AssignPartitionToOrphanNodes $COARSEN_GRAPH $ORPHANS $NUM_PARTITIONS 


hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.FinalPartitionMapping $WCC_OUT $ORPHANS $NODE_MAPPNG $BREAKPOINTS $NUM_PARTITIONS $NUM_REDUCERS


#hadoop jar /usr/local/giraphpp/target/giraph-0.2-SNAPSHOT-jar-with-dependencies.jar com.ibm.giraph.graph.example.coarsen.RecodeGraph $INPUT_GRAPH $NODE_MAPPNG $OUTPUT_GRAPH $NUM_NODES

